spring.application.name=MemberArticle
server.port=8080
# Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=ace
spring.datasource.password=ace
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
